address = "0x48216df3d955d9a8afd28d417ff21d06647e6a6d"
interface = [{u'constant': False,
              u'inputs': [],
              u'name': u'create_registry()',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'owner', u'type': u'int256'}],
              u'name': u'get_default_registry(int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'reg_id', u'type': u'int256'}],
              u'name': u'get_owner(int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'reg_id', u'type': u'int256'},
                          {u'name': u'key', u'type': u'int256'}],
              u'name': u'get_storage_key(int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'owner', u'type': u'int256'},
                          {u'name': u'key', u'type': u'int256'}],
              u'name': u'lookup(int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'reg_id', u'type': u'int256'},
                          {u'name': u'key', u'type': u'int256'}],
              u'name': u'lookup_by_id(int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'key', u'type': u'int256'},
                          {u'name': u'val', u'type': u'int256'}],
              u'name': u'register(int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'reg_id', u'type': u'int256'},
                          {u'name': u'key', u'type': u'int256'},
                          {u'name': u'val', u'type': u'int256'}],
              u'name': u'register_by_id(int256,int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'key', u'type': u'int256'}],
              u'name': u'remove(int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'keys', u'type': u'int256[]'}],
              u'name': u'remove2(int256[])',
              u'outputs': [{u'name': u'out', u'type': u'int256[]'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'reg_id', u'type': u'int256'},
                          {u'name': u'key', u'type': u'int256'}],
              u'name': u'remove_by_id(int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'reg_id', u'type': u'int256'},
                          {u'name': u'keys', u'type': u'int256[]'}],
              u'name': u'remove_by_id2(int256,int256[])',
              u'outputs': [{u'name': u'out', u'type': u'int256[]'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'reg_id', u'type': u'int256'}],
              u'name': u'set_default_registry(int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'new_owner', u'type': u'int256'},
                          {u'name': u'reg_id', u'type': u'int256'}],
              u'name': u'transfer_owner(int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'key', u'type': u'int256'},
                          {u'name': u'val', u'type': u'int256'}],
              u'name': u'update(int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'},
             {u'constant': False,
              u'inputs': [{u'name': u'reg_id', u'type': u'int256'},
                          {u'name': u'key', u'type': u'int256'},
                          {u'name': u'val', u'type': u'int256'}],
              u'name': u'update_by_id(int256,int256,int256)',
              u'outputs': [{u'name': u'out', u'type': u'int256'}],
              u'type': u'function'}]
